Another cmake file
elsid/newuoa-c pull request #3
Opened 2022-10-31 09:23 UTC by mhekkel

cmake has evolved and I'm using it now exclusively. The current CMakeLists.txt file in newuoa-cpp is a bit outdated and makes is rather hard to include newuoa embedded in other projects. The proposed update writes out cmake configuration files as well as a pkgconfig file making inclusion of this library easier.

2022-11-01 08:56 UTC, elsid requested changes

2022-11-01 08:56 UTC, elsid commented on CMakeLists.txt
> +project(newuoa VERSION 0.1.1 DESCRIPTION "C++ implementation of NEWUOA algorithm with C interface")
It worth to change version to 0.1.2 because there is already a tag for 0.1.1 https://github.com/elsid/newuoa-cpp/releases .

2022-11-01 08:56 UTC, elsid commented on CMakeLists.txt
> +install(FILES ${CMAKE_CURRENT_BINARY_DIR}/newuoa.pc DESTINATION ${CMAKE_INSTALL_LIBDIR}/pkgconfig)
Please add empty line at the end of the file.

2022-11-03 12:28 UTC, mhekkel commented
Change performed and checked in.

2022-11-04 00:26 UTC, merged

2022-11-04 00:26 UTC, elsid commented
Thanks.